### ISSUE TITLE
Gerar casos de testes PDF

### ISSUE THREAD

**Issue by rodrigoncalves** [lades-unb/pades-plugin#14]

**Comment by rodrigoncalves** [comment]
Link planilha do Drive: https://docs.google.com/spreadsheets/d/1NvlxKE0gBgsx7F5CJknHPs89SbdoCPFueAOcaV16vSk/edit#gid=1007539246

**Comment by DRA2840** [comment]
É possível já começar a testar o plugin? Não olhei o código, mas procurei um makefile e não achei. Tem como colocar as instruções no README?

**Comment by rodrigoncalves** [comment]
Em breve o executável do plugin será disponibilizado.
